version: "3"

# environment variables are taken from .env
services:
  postgresdb:
    image: postgres
    container_name: ting_postgres_container
    volumes: 
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ting_network
    restart: always
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z-37-ged264449b
    container_name: ting_minio_container
    volumes:
      - ./volumes/minio:/data
    ports:
      - ${MINIO_LOCAL_PORT}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_USER}
      MINIO_SECRET_KEY: ${MINIO_PASSWORD}
    command: "server /data"
    networks:
      - ting_network
    restart: always
  api:
    build: api
    container_name: ting_api_container
    ports:
      - ${API_LOCAL_PORT}:8080
    expose:
      - 8080
    environment:
      - ENVIRON=${ENVIRON} # set from command line with ENVIRON=dev docker-compose up ...
      - APP_NAME=TingApp
    depends_on:
      - "postgresdb"
      - "minio"
    networks:
      - ting_network
    restart: always
  nginx:
    build: nginx
    container_name: ting_nginx_container
    ports:
    - ${NGINX_LOCAL_PORT}:80
    networks:
      - ting_network
    restart: always

networks:
  ting_network:
    name: ting_network
    external: false # compose will create network by itself
  

