version: "3"

# environment variables are taken from .env
services:
  postgresdb:
    image: postgres
    container_name: ting_postgres_container
    volumes: 
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ting_network
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z-37-ged264449b
    container_name: ting_minio_container
    volumes:
      - ./volumes/minio:/data
    ports:
      - ${MINIO_LOCAL_PORT}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_USER}
      MINIO_SECRET_KEY: ${MINIO_PASSWORD}
    command: "server /data"
    networks:
      - ting_network
  api:
    build: api
    container_name: ting_api 
    ports:
      - ${API_LOCAL_PORT}:5000
    depends_on:
      - "postgresdb"
      - "minio"
    networks:
      - ting_network

networks:
  ting_network:
    name: ting_network
    external: false # compose will create network by itself
  

