version: '3'

# environment variables are taken from .env
services:
  postgresdb:
    image: postgres
    container_name: ting_postgres_container
    volumes: 
      - "./volumes/postgres:/var/lib/postgresql/data"
    networks:
      - ting_network
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  ting_network:
    name: ting_network
    external: false # compose will create network by itself

